name: release

on:
  # Temporary for testing:
  push:
    branches: [release-via-ci]
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "8"
      - name: Install Clojure dependencies
        run: lein deps
      - name: Deploy to Clojars
        run: lein deploy releases
        env:
          LEIN_PASSWORD: ${{ secrets.LEIN_PASSWORD }}
